"""new values

Revision ID: 54395c4477c1
Revises: 85c19b578868
Create Date: 2025-06-29 01:54:29.990926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.guest import StringList


# revision identifiers, used by Alembic.
revision: str = '54395c4477c1'
down_revision: Union[str, None] = '85c19b578868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('companionName', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('bus', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('childrenNames', StringList, nullable=True))
    op.add_column('guests', sa.Column('childrenAges', StringList, nullable=True))
    op.drop_column('guests', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('guests', 'childrenAges')
    op.drop_column('guests', 'childrenNames')
    op.drop_column('guests', 'bus')
    op.drop_column('guests', 'companionName')
    # ### end Alembic commands ###
