"""add is_attending and song_request

Revision ID: 85c19b578868
Revises: a36d58a41244
Create Date: 2025-06-15 18:28:14.075525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c19b578868'
down_revision: Union[str, None] = 'a36d58a41244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('isAttending', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('guests', sa.Column('allergies', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('songRequests', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('children', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('tomorrowland', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'tomorrowland')
    op.drop_column('guests', 'children')
    op.drop_column('guests', 'songRequests')
    op.drop_column('guests', 'allergies')
    op.drop_column('guests', 'isAttending')
    # ### end Alembic commands ###
