"""new timestamp

Revision ID: 9b1436a9580a
Revises: 54395c4477c1
Create Date: 2025-06-29 02:08:18.204617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1436a9580a'
down_revision: Union[str, None] = '54395c4477c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'createdAt')
    # ### end Alembic commands ###
